services:
  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: airports
      POSTGRES_USER: crystaline
